name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop
      - "releases/*"

jobs:
  units: # unit tests
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "21.7.3"
          cache: "npm"
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm test
