name: Tests

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  units: # unit tests
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm install -g npm@latest
    - run: npm ci
    - run: npm test
